// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDF1Se_hsBQXhR-9SLerX1AjawQAEN4-Mk',
    appId: '1:631196759272:web:fa0de67f92ddbc2482455d',
    messagingSenderId: '631196759272',
    projectId: 'careaiproject',
    authDomain: 'careaiproject.firebaseapp.com',
    storageBucket: 'careaiproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2HIor50NBnXT3jF06iZMIdasylmKyUGc',
    appId: '1:631196759272:android:c325434eb553c4c082455d',
    messagingSenderId: '631196759272',
    projectId: 'careaiproject',
    storageBucket: 'careaiproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu8AcMtAgnCvnfo2uWFLvN2myrcCegfnY',
    appId: '1:631196759272:ios:f8d5857baea9db3482455d',
    messagingSenderId: '631196759272',
    projectId: 'careaiproject',
    storageBucket: 'careaiproject.appspot.com',
    iosBundleId: 'com.example.careai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDu8AcMtAgnCvnfo2uWFLvN2myrcCegfnY',
    appId: '1:631196759272:ios:f8d5857baea9db3482455d',
    messagingSenderId: '631196759272',
    projectId: 'careaiproject',
    storageBucket: 'careaiproject.appspot.com',
    iosBundleId: 'com.example.careai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDF1Se_hsBQXhR-9SLerX1AjawQAEN4-Mk',
    appId: '1:631196759272:web:563db7f894e34c8282455d',
    messagingSenderId: '631196759272',
    projectId: 'careaiproject',
    authDomain: 'careaiproject.firebaseapp.com',
    storageBucket: 'careaiproject.appspot.com',
  );

}